print(10+5)
print(10-5)
print(10*5)
print(10/5)

print('Hello')
print("Hello")
print("Hello'world'")
print('Hello"world"')

print('Hello'+'world')
print('Hello'*3)
print('Hello'[0])
print('Hello'[1])
print('Hello'[2])

print('hello world'.capitalize())
print('hello world'.upper())
print('hello world'.__len__())
print(len('Hello world'))
print('Hello world'.replace('world','programing'))

print("egoing's\"tutorial\"")
print("\\")
print("Hello\t\tworld")
print("\a")
print("Hello\nworld")

print(10+5)
print("10"+"5")